// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Pet struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	TypeID int32  `json:"type_id"`
	Age    int32  `json:"age"`
	UserID int32  `json:"user_id"`
}

type PetType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
